CREATE TABLE card (
  id BINARY(16) NOT NULL PRIMARY KEY,
  pan_hash BINARY(32) NOT NULL UNIQUE,
  pan_enc VARBINARY(512) NOT NULL,
  pan_iv VARBINARY(12) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
